/**
 * Read-only export of the npm house spec into shared Kotlin.
 * Does not write src/, public/, package.json, or TASKS.md.
 *
 *   node tools/kmp/export-spec.mjs
 */
import { createServer } from "vite";
import { writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const outFile = resolve(
  root,
  "shared/src/commonMain/kotlin/com/neojou/japanesehouse3d/domain/HouseSpec.kt",
);
const interactFile = resolve(
  root,
  "shared/src/commonMain/kotlin/com/neojou/japanesehouse3d/domain/HouseInteract.kt",
);
const interactOnly = process.argv.includes("--interact-only");

const vite = await createServer({
  configFile: resolve(root, "vite.config.ts"),
  server: { middlewareMode: true },
  appType: "custom",
});

try {
  const dims = await vite.ssrLoadModule("/src/data/dimensions.ts");
  const height = await vite.ssrLoadModule("/src/lib/height.ts");
  const mats = await vite.ssrLoadModule("/src/lib/houseMaterials.ts");
  const ub = await vite.ssrLoadModule("/src/lib/ubBathHero.ts");
  const louver = await vite.ssrLoadModule("/src/lib/ubLouver.ts");
  const tubWater = await vite.ssrLoadModule("/src/lib/tubWater.ts");
  if (interactOnly) {
    writeFileSync(interactFile, renderInteract(dims, ub, louver, tubWater));
    console.log("wrote", interactFile);
  } else {
    writeFileSync(outFile, render(dims, height, mats, ub, louver));
    console.log("wrote", outFile);
  }
} finally {
  await vite.close();
}

function renderInteract(d, ub, louver, tubWater) {
  const swings = d.SWING_DOORS.map((def) => swingRec(d, def));
  const slides = d.SLIDE_DOORS.map((def) => slideRec(d, def));
  const folds = d.FOLD_DOORS.map((def) => foldRec(d, def));
  const genkan = genkanRec(d);
  const kitchen = d.PROP_1F_LDK_KITCHEN;
  const pi = d.PROP_1F_SENMEN.piara;
  const tub = tubRec(d, ub);
  const lou = louverRec(d, louver);
  const toilet = d.SIT_TOILET;
  const sink = d.PROP_2F_SINK;
  const rates = tubWater.TUB_WATER;
  const lines = [];
  lines.push(`// Generated by tools/kmp/export-spec.mjs --interact-only — do not edit numbers.
// Source: src/data/dimensions.ts, src/lib/ubBathHero.ts, src/lib/ubLouver.ts, src/lib/tubWater.ts
package com.neojou.japanesehouse3d.domain

object HouseInteract {
    const val swingDamp = 10.0
    const val slideDamp = 8.0
    const val foldDamp = 8.0
    const val genkanDamp = 10.0
    const val drawerDamp = 8.0
    const val streamDamp = 10.0
    const val louverDamp = 8.0
    const val toiletDamp = 7.0
    const val plugDamp = 14.0

    data class Swing(
        val id: String,
        val leafId: String,
        val axis: String,
        val hingeAt: String,
        val openSign: Int,
        val openAngleDeg: Double,
        val hingeX: Double,
        val hingeY: Double,
        val hingeZ: Double,
        val centerX: Double,
        val centerY: Double,
        val centerZ: Double,
        val sizeX: Double,
        val sizeY: Double,
        val sizeZ: Double,
    )

    data class Slide(
        val id: String,
        val axis: String,
        val overlap: Boolean,
        val panels: Int,
        val stack: Double,
        val pocketA: Double,
        val pocketB: Double,
        val leafA: String,
        val leafB: String,
    )

    data class Fold(
        val id: String,
        val leafId: String,
        val axis: String,
        val hingeAt: String,
        val openSign: Int,
        val openAngleDeg: Double,
        val hingeX: Double,
        val hingeY: Double,
        val hingeZ: Double,
        val panelW: Double,
        val leafW: Double,
        val leafH: Double,
        val thick: Double,
    )

    data class Genkan(
        val openRad: Double,
        val hingeX: Double,
        val hingeY: Double,
        val hingeZ: Double,
        val centerX: Double,
        val centerY: Double,
        val centerZ: Double,
        val sizeX: Double,
        val sizeY: Double,
        val sizeZ: Double,
    )

    val swings: List<Swing> = listOf(
${swings.map(swingKt).join(",\n")},
    )

    val slides: List<Slide> = listOf(
${slides.map(slideKt).join(",\n")},
    )

    val folds: List<Fold> = listOf(
${folds.map(foldKt).join(",\n")},
    )

    val genkan = Genkan(${num(genkan.openRad)}, ${num(genkan.hingeX)}, ${num(genkan.hingeY)}, ${num(genkan.hingeZ)}, ${num(genkan.centerX)}, ${num(genkan.centerY)}, ${num(genkan.centerZ)}, ${num(genkan.sizeX)}, ${num(genkan.sizeY)}, ${num(genkan.sizeZ)})

    const val kitchenDrawerTravel = ${num(kitchen.drawerTravel)}
    const val kitchenStreamX = 0.4
    const val kitchenStreamY = 0.86
    const val kitchenStreamZ = 1.46
    const val kitchenStreamH = 0.26
    const val kitchenStreamR0 = 0.004
    const val kitchenStreamR1 = 0.005

    const val piaraDrawerTravel = ${num(pi.drawerTravel)}
    const val piaraDoorOpen = ${num(pi.doorOpen)}
    const val piaraMirrorOpen = ${num(pi.mirrorOpen)}
    const val piaraStreamX = ${num(pi.stream.x)}
    const val piaraStreamY = ${num(pi.stream.y)}
    const val piaraStreamZ = ${num(pi.stream.z)}
    const val piaraStreamH = ${num(pi.stream.h)}

    const val louverClosedDeg = ${num(lou.closedDeg)}
    const val louverOpenDeg = ${num(lou.openDeg)}
    const val louverSliderTravel = 0.28

    const val lidOpenRad = ${num(toilet.lidOpenRad)}
    const val seatOpenRad = ${num(toilet.seatOpenRad)}

    const val dokoStreamX = ${num(sink.stream.x)}
    const val dokoStreamY = ${num(sink.stream.y)}
    const val dokoStreamZ = ${num(sink.stream.z)}
    const val dokoStreamH = ${num(sink.stream.h)}

    const val tubFillRate = ${num(rates.fillRate)}
    const val tubDrainRate = ${num(rates.drainRate)}
    const val tubSpreadRate = ${num(rates.spreadRate)}
    const val tubDryRate = ${num(rates.dryRate)}

    data class Tub(
        val x: Double,
        val y: Double,
        val z: Double,
        val length: Double,
        val width: Double,
        val innerW: Double,
        val innerL: Double,
        val bottomY: Double,
        val brimY: Double,
        val spillY: Double,
        val plugTravel: Double,
        val buttonTravel: Double,
        val tipX: Double,
        val tipY: Double,
        val tipZ: Double,
        val holeX: Double,
        val holeY: Double,
        val holeZ: Double,
        val r: Double,
        val g: Double,
        val b: Double,
        val a: Double,
    )

    val tub = Tub(${num(tub.x)}, ${num(tub.y)}, ${num(tub.z)}, ${num(tub.length)}, ${num(tub.width)}, ${num(tub.innerW)}, ${num(tub.innerL)}, ${num(tub.bottomY)}, ${num(tub.brimY)}, ${num(tub.spillY)}, ${num(tub.plugTravel)}, ${num(tub.buttonTravel)}, ${num(tub.tipX)}, ${num(tub.tipY)}, ${num(tub.tipZ)}, ${num(tub.holeX)}, ${num(tub.holeY)}, ${num(tub.holeZ)}, ${num(tub.r)}, ${num(tub.g)}, ${num(tub.b)}, ${num(tub.a)})

    val animatedBoxIds: Set<String> = setOf(
${animatedIds(swings, slides, folds).map((id) => `        "${id}"`).join(",\n")},
    )
}
`);
  return lines.join("\n");
}

function swingRec(d, def) {
  const FRAME = 0.05;
  const LEAF_T = 0.04;
  const leafW = Math.abs(def.alongMax - def.alongMin) - 0.02;
  const leafH = def.height - FRAME - 0.01;
  const baseY = d.FLOOR_LEVELS[def.floor ?? "1f"];
  const sillY = baseY + def.sill;
  const hingeAlong = def.hingeAt === "min" ? def.alongMin : def.alongMax;
  const leafDir = def.hingeAt === "min" ? 1 : -1;
  const midY = sillY + leafH / 2;
  const hx = def.axis === "ew" ? hingeAlong : def.wallX;
  const hz = def.axis === "ew" ? def.wallZ : hingeAlong;
  const cx = def.axis === "ew" ? hingeAlong + leafDir * leafW / 2 : def.wallX;
  const cz = def.axis === "ew" ? def.wallZ : hingeAlong + leafDir * leafW / 2;
  const sx = def.axis === "ew" ? leafW : LEAF_T;
  const sz = def.axis === "ew" ? LEAF_T : leafW;
  return {
    id: def.id,
    leafId: `${def.id}-leaf`,
    axis: def.axis,
    hingeAt: def.hingeAt,
    openSign: def.openSign,
    openAngleDeg: def.openAngleDeg,
    hingeX: hx,
    hingeY: midY,
    hingeZ: hz,
    centerX: cx,
    centerY: midY,
    centerZ: cz,
    sizeX: sx,
    sizeY: leafH,
    sizeZ: sz,
  };
}

function slideRec(d, def) {
  const openingW = Math.abs(def.alongMax - def.alongMin);
  const n = def.panels;
  const overlap = 0.04;
  const leafW = n === 2 ? (openingW + overlap) / 2 + 0.01 : openingW - 0.02;
  const dir = def.openToward === "min" ? -1 : 1;
  const stack = leafW - overlap;
  return {
    id: def.id,
    axis: def.axis,
    overlap: def.slideStyle === "overlap" && n === 2,
    panels: n,
    stack,
    pocketA: dir * leafW * 0.88,
    pocketB: dir * (leafW * 0.88 + leafW * 0.72),
    leafA: `${def.id}-a`,
    leafB: `${def.id}-b`,
  };
}

function foldRec(d, def) {
  const openingW = Math.abs(def.alongMax - def.alongMin);
  const panelW = openingW / 2;
  const leafW = panelW - 0.003;
  const leafH = def.height - 0.045;
  const baseY = d.FLOOR_LEVELS[def.floor ?? "1f"];
  const sillY = baseY + def.sill;
  const hingeAlong = def.hingeAt === "min" ? def.alongMin : def.alongMax;
  const hx = def.axis === "ew" ? hingeAlong : def.wallX;
  const hz = def.axis === "ew" ? def.wallZ : hingeAlong;
  return {
    id: def.id,
    leafId: `${def.id}-leaf`,
    axis: def.axis,
    hingeAt: def.hingeAt,
    openSign: def.openSign,
    openAngleDeg: def.openAngleDeg,
    hingeX: hx,
    hingeY: sillY,
    hingeZ: hz,
    panelW,
    leafW,
    leafH,
    thick: 0.04,
  };
}

function genkanRec(d) {
  const g = d.GENKAN_ENTRY;
  const halfT = d.BUILDING.wallThickness / 2;
  const leafT = 0.052;
  const hingeX = g.x0 + 0.05;
  const leafZ = g.z - halfT + leafT / 2 + 0.002;
  const frameBaseY = d.FLOOR_LEVELS["1f"] + g.sill;
  const leafW = g.openingWidth - 0.1;
  const leafH = g.openingHeight - 0.02;
  return {
    openRad: (g.openAngleDeg * Math.PI) / 180,
    hingeX,
    hingeY: frameBaseY + leafH / 2,
    hingeZ: leafZ,
    centerX: hingeX + leafW / 2,
    centerY: frameBaseY + leafH / 2,
    centerZ: leafZ,
    sizeX: leafW,
    sizeY: leafH,
    sizeZ: leafT,
  };
}

function tubRec(d, ub) {
  const p = d.PROP_1F_UB_TUB;
  const spout = ub.spoutTipPlan();
  const hole = ub.drainHolePlan();
  const floorY = p.y;
  const color = hexRgb(p.water.color);
  return {
    x: p.x,
    y: p.y,
    z: p.z,
    length: p.length,
    width: p.width,
    innerW: p.width - 2 * p.innerInset,
    innerL: p.length - 2 * p.innerInset,
    bottomY: floorY + p.rimH - p.basinDepth + 0.012,
    brimY: floorY + p.rimH - p.water.insetY,
    spillY: floorY + p.rimH - 0.008,
    plugTravel: p.drain.travel,
    buttonTravel: p.plug.travel,
    tipX: spout.x,
    tipY: spout.y - p.faucet.spoutDrop,
    tipZ: spout.z,
    holeX: hole.x,
    holeY: hole.y,
    holeZ: hole.z,
    r: color.r,
    g: color.g,
    b: color.b,
    a: p.water.opacity,
  };
}

function louverRec(d) {
  return { closedDeg: d.PROP_1F_UB_LOUVER.closedDeg, openDeg: d.PROP_1F_UB_LOUVER.openDeg };
}

function swingKt(s) {
  return `        Swing("${s.id}", "${s.leafId}", "${s.axis}", "${s.hingeAt}", ${s.openSign}, ${num(s.openAngleDeg)}, ${num(s.hingeX)}, ${num(s.hingeY)}, ${num(s.hingeZ)}, ${num(s.centerX)}, ${num(s.centerY)}, ${num(s.centerZ)}, ${num(s.sizeX)}, ${num(s.sizeY)}, ${num(s.sizeZ)})`;
}

function slideKt(s) {
  return `        Slide("${s.id}", "${s.axis}", ${s.overlap}, ${s.panels}, ${num(s.stack)}, ${num(s.pocketA)}, ${num(s.pocketB)}, "${s.leafA}", "${s.leafB}")`;
}

function foldKt(s) {
  return `        Fold("${s.id}", "${s.leafId}", "${s.axis}", "${s.hingeAt}", ${s.openSign}, ${num(s.openAngleDeg)}, ${num(s.hingeX)}, ${num(s.hingeY)}, ${num(s.hingeZ)}, ${num(s.panelW)}, ${num(s.leafW)}, ${num(s.leafH)}, ${num(s.thick)})`;
}

function animatedIds(swings, slides, folds) {
  const ids = [];
  for (const s of swings) ids.push(s.leafId);
  for (const s of slides) {
    ids.push(s.leafA);
    if (s.panels === 2) ids.push(s.leafB);
  }
  for (const s of folds) ids.push(s.leafId);
  return ids;
}

function render(d, height, mats, ub, louver) {
  const boxes = [];
  const push = (id, x, y, z, sx, sy, sz, finish, yaw = 0) => {
    if (!(sx > 0.004 && sy > 0.004 && sz > 0.004)) return;
    const look = finishLook(finish, d, mats);
    boxes.push({ id, x, y, z, sx, sy, sz, yaw, ...look });
  };

  for (const wall of d.WALLS) {
    const finish = mats.wallFinishForId(wall.id);
    for (const piece of solidPieces(wall, d)) {
      push(piece.key, piece.x, piece.y, piece.z, piece.sizeX, piece.sizeY, piece.sizeZ, finish);
    }
  }

  for (const slab of d.ALL_FLOOR_SLABS) {
    const look = floorFinish(slab, d);
    const { rect } = slab;
    push(
      slab.id,
      rect.x + rect.width / 2,
      slab.y - slab.thickness / 2,
      rect.z + rect.depth / 2,
      rect.width,
      slab.thickness,
      rect.depth,
      look,
    );
  }

  for (const slab of d.ALL_CEILINGS) {
    if (
      slab.id === "ceil-ph-hall" ||
      slab.id === "ceil-2f-ne" ||
      slab.id === "ceil-2f-ne-cl" ||
      slab.id === "ceil-2f-ne-foyer"
    ) {
      continue;
    }
    const { rect } = slab;
    push(
      slab.id,
      rect.x + rect.width / 2,
      slab.y - slab.thickness / 2,
      rect.z + rect.depth / 2,
      rect.width,
      slab.thickness,
      rect.depth,
      "ceiling",
    );
  }

  for (const flight of d.STAIRS) pushFlight(push, flight, d);
  for (const winder of d.STAIR_WINDERS) pushWinder(push, winder, d);
  pushDoors(push, d);
  pushSite(push, d);
  pushRoofs(push, d);

  const heroes = heroList(d, ub, louver);
  const samples = heightSamples(d, height);
  const lights = lightList(d);

  const chunks = [];
  for (let i = 0; i < boxes.length; i += 40) {
    const part = boxes.slice(i, i + 40);
    const n = chunks.length;
    chunks.push(
      `    private fun boxes${n}(): List<Box> = listOf(\n${part.map(boxKt).join(",\n")},\n    )\n`,
    );
  }
  const concat = chunks.map((_, i) => `boxes${i}()`).join(" + ");

  return `// Generated by tools/kmp/export-spec.mjs — do not edit numbers.
// Source: src/data/dimensions.ts, src/lib/height.ts, src/lib/houseMaterials.ts
package com.neojou.japanesehouse3d.domain

object HouseSpec {
    const val width = ${num(d.BUILDING.width)}
    const val depth = ${num(d.BUILDING.depth)}
    const val wallThickness = ${num(d.BUILDING.wallThickness)}
    const val wallHeight = ${num(d.storyWallHeight("1f"))}
    const val floorHeight = ${num(d.BUILDING.floorHeight)}
    const val grade = 0.0
    const val interior1f = ${num(d.STORY.floor1f)}
    const val story2f = ${num(d.STORY.floor2f)}
    const val ph = ${num(d.STORY.floorPh)}
    const val peak = ${num(d.STORY.peak)}
    const val ldkE = ${num(d.SX.xLdkE)}
    const val genkanE = ${num(d.SX.xGenkanE)}
    const val sclE = ${num(d.SX.xSclE)}
    const val recessZ = ${num(d.SZ.recess)}
    const val ubSouthZ = ${num(d.SZ.ubSouth)}
    const val spawnX = ${num(d.PLAYER.spawn.x)}
    const val spawnZ = ${num(d.PLAYER.spawn.z)}
    const val eyeHeight = ${num(d.PLAYER.eyeHeight)}
    const val moveSpeed = ${num(d.PLAYER.moveSpeed)}
    const val turnDegrees = ${num(d.PLAYER.turnDegrees)}
    const val lookSensitivity = ${num(d.PLAYER.lookSensitivity)}
    const val interiorFloorY = ${num(d.INTERIOR_FLOOR_Y)}
    const val maxStepUp = ${num(height.MAX_STEP_UP)}
    const val maxStepDown = ${num(height.MAX_STEP_DOWN)}
    const val feetIgnore2fBelow = ${num(height.FEET_Y_IGNORE_2F_BELOW)}
    const val feetIgnorePhBelow = ${num(height.FEET_Y_IGNORE_PH_BELOW)}
    const val y2fSlabMin = 3.2
    const val yPhSlabMin = 5.8
    const val stairPad = 0.14
    const val winderAngPad = 0.22
    const val background = 0x${hex(d.LIGHTING.background)}
    const val sunR = ${num(hexRgb(d.LIGHTING.sun.color).r)}
    const val sunG = ${num(hexRgb(d.LIGHTING.sun.color).g)}
    const val sunB = ${num(hexRgb(d.LIGHTING.sun.color).b)}
    const val sunIntensity = ${num(d.LIGHTING.sun.intensity)}
    const val sunX = ${num(d.LIGHTING.sun.position[0])}
    const val sunY = ${num(d.LIGHTING.sun.position[1])}
    const val sunZ = ${num(d.LIGHTING.sun.position[2])}
    const val ambient = ${num(d.LIGHTING.ambient)}
    const val hemiIntensity = ${num(d.LIGHTING.hemiIntensity)}
    const val fogNear = ${num(d.LIGHTING.fogNear)}
    const val fogFar = ${num(d.LIGHTING.fogFar)}

    data class Box(
        val id: String,
        val x: Double,
        val y: Double,
        val z: Double,
        val sx: Double,
        val sy: Double,
        val sz: Double,
        val yaw: Double,
        val r: Double,
        val g: Double,
        val b: Double,
        val rough: Double,
        val metal: Double,
        val finish: String,
    )

    data class Slab(
        val id: String,
        val floor: String,
        val y: Double,
        val x: Double,
        val z: Double,
        val w: Double,
        val d: Double,
    )

    data class Stair(
        val id: String,
        val x: Double,
        val z: Double,
        val direction: String,
        val stepCount: Int,
        val treadDepth: Double,
        val riserHeight: Double,
        val width: Double,
        val baseY: Double,
    )

    data class Winder(
        val id: String,
        val pivotX: Double,
        val pivotZ: Double,
        val rInner: Double,
        val rOuter: Double,
        val startAngle: Double,
        val sweep: Double,
        val stepCount: Int,
        val riserHeight: Double,
        val baseY: Double,
    )

    data class Hero(
        val file: String,
        val x: Double,
        val y: Double,
        val z: Double,
        val yaw: Double,
    )

    data class Fill(
        val id: String,
        val x: Double,
        val y: Double,
        val z: Double,
        val intensity: Double,
        val distance: Double,
        val r: Double,
        val g: Double,
        val b: Double,
    )

    data class HeightSample(
        val name: String,
        val x: Double,
        val z: Double,
        val feet: Double,
        val y: Double,
    )

${chunks.join("\n")}
    val boxes: List<Box> = ${concat}

    val slabs: List<Slab> = listOf(
${d.ALL_FLOOR_SLABS.map((s) => `        Slab("${esc(s.id)}", "${s.floor}", ${num(s.y)}, ${num(s.rect.x)}, ${num(s.rect.z)}, ${num(s.rect.width)}, ${num(s.rect.depth)}),`).join("\n")}
    )

    val stairs: List<Stair> = listOf(
${d.STAIRS.map((s) => `        Stair("${esc(s.id)}", ${num(s.x)}, ${num(s.z)}, "${s.direction}", ${s.stepCount}, ${num(s.treadDepth)}, ${num(s.riserHeight)}, ${num(s.width)}, ${num(s.baseY)}),`).join("\n")}
    )

    val winders: List<Winder> = listOf(
${d.STAIR_WINDERS.map((w) => `        Winder("${esc(w.id)}", ${num(w.pivotX)}, ${num(w.pivotZ)}, ${num(w.rInner)}, ${num(w.rOuter)}, ${num(w.startAngle)}, ${num(w.sweep)}, ${w.stepCount}, ${num(w.riserHeight)}, ${num(w.baseY)}),`).join("\n")}
    )

    val heroes: List<Hero> = listOf(
${heroes.map((h) => `        Hero("${h.file}", ${num(h.x)}, ${num(h.y)}, ${num(h.z)}, ${num(h.yaw)}),`).join("\n")}
    )

    val fills: List<Fill> = listOf(
${lights.map((f) => `        Fill("${esc(f.id)}", ${num(f.x)}, ${num(f.y)}, ${num(f.z)}, ${num(f.intensity)}, ${num(f.distance)}, ${num(f.r)}, ${num(f.g)}, ${num(f.b)}),`).join("\n")}
    )

    val heightSamples: List<HeightSample> = listOf(
${samples.map((s) => `        HeightSample("${esc(s.name)}", ${num(s.x)}, ${num(s.z)}, ${num(s.feet)}, ${num(s.y)}),`).join("\n")}
    )

    val genkanX0 = ${num(d.GENKAN_ENTRY.x0)}
    val genkanX1 = ${num(d.GENKAN_ENTRY.x1)}
    val genkanZ = ${num(d.GENKAN_ENTRY.z)}
    val genkanStepWidth = ${num(d.GENKAN_ENTRY.stepWidth)}
    val genkanStepDepth = ${num(d.GENKAN_ENTRY.stepDepth)}
    val genkanStepHeight = ${num(d.GENKAN_ENTRY.stepHeight)}
    val genkanStepCount = ${d.GENKAN_ENTRY.stepCount}
}
`;
}

function boxKt(b) {
  return `        Box("${esc(b.id)}", ${num(b.x)}, ${num(b.y)}, ${num(b.z)}, ${num(b.sx)}, ${num(b.sy)}, ${num(b.sz)}, ${num(b.yaw)}, ${num(b.r)}, ${num(b.g)}, ${num(b.b)}, ${num(b.rough)}, ${num(b.metal)}, "${b.finish}")`;
}

function num(n) {
  if (!Number.isFinite(n)) throw new Error("bad number " + n);
  const rounded = Math.round(n * 1e9) / 1e9;
  const text = Object.is(rounded, -0) ? "0" : String(rounded);
  if (text.includes("e") || text.includes("E")) {
    return rounded.toFixed(9).replace(/0+$/, "").replace(/\.$/, ".0");
  }
  return text.includes(".") ? text : `${text}.0`;
}

function esc(s) {
  return String(s).replace(/\\/g, "\\\\").replace(/"/g, '\\"');
}

function hex(css) {
  return String(css).replace("#", "").slice(0, 6);
}

function hexRgb(css) {
  const h = hex(css);
  return {
    r: parseInt(h.slice(0, 2), 16) / 255,
    g: parseInt(h.slice(2, 4), 16) / 255,
    b: parseInt(h.slice(4, 6), 16) / 255,
  };
}

function finishLook(finish, d, mats) {
  const C = d.COLORS;
  const P = d.MATERIAL_PRESETS;
  const map = {
    stucco: { color: "#ffffff", ...P.wallExterior, finish: "stucco" },
    yakiSugi: { color: C.yakiSugi, rough: 0.86, metal: 0, finish: "yaki" },
    interiorMain: { color: mats.INTERIOR.main, ...P.wallInterior, finish: "paint" },
    interiorSecondary: { color: mats.INTERIOR.secondary, ...P.wallInterior, finish: "paint" },
    interiorAccent: { color: mats.INTERIOR.accent, rough: 0.8, metal: 0.02, finish: "paint" },
    interiorWood: { color: mats.INTERIOR.wood, rough: 0.62, metal: 0, finish: "paint" },
    bathMarble: { color: "#e7e4df", rough: 0.35, metal: 0.04, finish: "paint" },
    floor: { color: C.floor, ...P.floorInterior, finish: "paint" },
    floorOutdoor: { color: C.floorOutdoor, ...P.floorOutdoor, finish: "paint" },
    floorStair: { color: C.floorStair, ...P.floorStair, finish: "paint" },
    floorGenkan: { color: d.GENKAN_INTERIOR.floorColor, rough: 0.9, metal: 0.03, finish: "paint" },
    floorBath: { color: "#a8acb0", rough: 0.86, metal: 0.04, finish: "paint" },
    stair: { color: C.stair, ...P.stair, finish: "paint" },
    ceiling: { color: C.ceiling, ...P.ceiling, finish: "paint" },
    door: { color: C.genkanDoor, ...P.doorWood, finish: "paint" },
    doorOak: { color: "#d2c3b0", rough: 0.48, metal: 0.02, finish: "paint" },
    doorFrame: { color: mats.INTERIOR.accent, ...P.doorFrame, finish: "paint" },
    glass: { color: C.glass, ...P.glass, finish: "glass" },
    parking: { color: C.parking, ...P.parking, finish: "paint" },
    ground: { color: C.ground, ...P.ground, finish: "paint" },
    step: { color: "#4a4844", rough: 0.92, metal: 0.02, finish: "paint" },
    roof: { color: "#6a6560", rough: 0.92, metal: 0.02, finish: "paint" },
    roofDark: { color: "#5c5854", rough: 0.92, metal: 0.02, finish: "paint" },
  };
  const row = map[finish] ?? map.interiorMain;
  const rgb = hexRgb(row.color);
  return {
    r: rgb.r,
    g: rgb.g,
    b: rgb.b,
    rough: row.roughness ?? row.rough ?? 0.8,
    metal: row.metalness ?? row.metal ?? 0,
    finish: row.finish,
  };
}

function floorFinish(slab, d) {
  const id = slab.id;
  if (d.GENKAN_INTERIOR.floorIds.includes(id)) return "floorGenkan";
  if (d.UB_BATH.floorIds.includes(id)) return "floorBath";
  if (id.includes("balc") || id.includes("balcony") || id.includes("parking")) return "floorOutdoor";
  if (id.includes("stair") || id.includes("deck") || id.includes("landing") || id.includes("approach")) {
    return "floorStair";
  }
  return "floor";
}

function solidPieces(wall, d) {
  const wallHeight = wall.height ?? d.storyWallHeight(wall.floor);
  const baseY = d.FLOOR_LEVELS[wall.floor];
  const openings = wall.openings ?? [];
  const alongX = wall.lengthX >= wall.lengthZ;
  if (openings.length === 0) {
    return [{
      key: wall.id,
      x: wall.x,
      y: baseY + wallHeight / 2,
      z: wall.z,
      sizeX: wall.lengthX,
      sizeY: wallHeight,
      sizeZ: wall.lengthZ,
    }];
  }
  const sorted = [...openings].sort((a, b) => a.fromStart - b.fromStart);
  const length = alongX ? wall.lengthX : wall.lengthZ;
  const thickness = alongX ? wall.lengthZ : wall.lengthX;
  const startCoord = alongX ? wall.x - wall.lengthX / 2 : wall.z - wall.lengthZ / 2;
  const pieces = [];
  let cursor = 0;
  const pushFull = (from, to, key) => {
    const segLen = to - from;
    if (segLen < 0.01) return;
    const mid = startCoord + (from + to) / 2;
    pieces.push({
      key,
      x: alongX ? mid : wall.x,
      y: baseY + wallHeight / 2,
      z: alongX ? wall.z : mid,
      sizeX: alongX ? segLen : thickness,
      sizeY: wallHeight,
      sizeZ: alongX ? thickness : segLen,
    });
  };
  const pushBand = (opening, y0, y1, key) => {
    const h = y1 - y0;
    if (h < 0.01) return;
    const mid = startCoord + opening.fromStart + opening.width / 2;
    pieces.push({
      key,
      x: alongX ? mid : wall.x,
      y: baseY + (y0 + y1) / 2,
      z: alongX ? wall.z : mid,
      sizeX: alongX ? opening.width : thickness,
      sizeY: h,
      sizeZ: alongX ? thickness : opening.width,
    });
  };
  sorted.forEach((opening, i) => {
    const a = Math.max(0, Math.min(length, opening.fromStart));
    const b = Math.max(0, Math.min(length, opening.fromStart + opening.width));
    pushFull(cursor, a, `${wall.id}-solid-${i}`);
    const sill = opening.sill ?? 0;
    const openTop = sill + opening.height;
    pushBand(opening, 0, sill, `${wall.id}-sill-${i}`);
    pushBand(opening, openTop, wallHeight, `${wall.id}-lintel-${i}`);
    cursor = Math.max(cursor, b);
  });
  pushFull(cursor, length, `${wall.id}-solid-end`);
  return pieces;
}

function pushFlight(push, flight, d) {
  const alongX = flight.direction === "east" || flight.direction === "west";
  const sign = flight.direction === "south" || flight.direction === "west" ? -1 : 1;
  for (let i = 0; i < flight.stepCount; i++) {
    const along = (i + 0.5) * flight.treadDepth * sign;
    const x = flight.x + (alongX ? along : 0);
    const z = flight.z + (alongX ? 0 : along);
    const y = flight.baseY + (i + 0.5) * flight.riserHeight;
    const sizeX = alongX ? flight.treadDepth : flight.width;
    const sizeZ = alongX ? flight.width : flight.treadDepth;
    push(`${flight.id}-step-${i}`, x, y, z, sizeX, flight.riserHeight, sizeZ, "stair");
  }
}

function pushWinder(push, winder) {
  const n = winder.stepCount;
  const rMid = (winder.rInner + winder.rOuter) / 2;
  const radial = winder.rOuter - winder.rInner;
  const dAng = winder.sweep / n;
  for (let i = 0; i < n; i++) {
    const aMid = winder.startAngle + (i + 0.5) * dAng;
    const x = winder.pivotX + rMid * Math.cos(aMid);
    const z = winder.pivotZ + rMid * Math.sin(aMid);
    const y = winder.baseY + (i + 0.5) * winder.riserHeight;
    const chord = Math.abs(rMid * dAng) * 1.05;
    const yaw = -(aMid + Math.PI / 2);
    push(`${winder.id}-w-${i}`, x, y, z, chord, winder.riserHeight, radial, "stair", yaw);
  }
}

function pushDoors(push, d) {
  const T = d.BUILDING.wallThickness;
  const FRAME = 0.05;
  const LEAF_T = 0.04;
  for (const def of d.SWING_DOORS) {
    const leafW = Math.abs(def.alongMax - def.alongMin) - 0.02;
    const leafH = def.height - FRAME - 0.01;
    const baseY = d.FLOOR_LEVELS[def.floor ?? "1f"];
    const sillY = baseY + def.sill;
    const hingeAlong = def.hingeAt === "min" ? def.alongMin : def.alongMax;
    const leafDir = def.hingeAt === "min" ? 1 : -1;
    const midY = sillY + leafH / 2;
    const oak = def.leaf ? "doorOak" : "door";
    const frame = def.leaf ? "doorOak" : "doorFrame";
    if (def.axis === "ew") {
      push(`${def.id}-post-a`, def.alongMin + FRAME / 2, sillY + def.height / 2, def.wallZ, FRAME, def.height, T, frame);
      push(`${def.id}-post-b`, def.alongMax - FRAME / 2, sillY + def.height / 2, def.wallZ, FRAME, def.height, T, frame);
      push(`${def.id}-head`, (def.alongMin + def.alongMax) / 2, sillY + def.height - FRAME / 2, def.wallZ, leafW + 0.02, FRAME, T, frame);
      push(`${def.id}-leaf`, hingeAlong + leafDir * leafW / 2, midY, def.wallZ, leafW, leafH, LEAF_T, oak);
    } else {
      push(`${def.id}-post-a`, def.wallX, sillY + def.height / 2, def.alongMin + FRAME / 2, T, def.height, FRAME, frame);
      push(`${def.id}-post-b`, def.wallX, sillY + def.height / 2, def.alongMax - FRAME / 2, T, def.height, FRAME, frame);
      push(`${def.id}-head`, def.wallX, sillY + def.height - FRAME / 2, (def.alongMin + def.alongMax) / 2, T, FRAME, leafW + 0.02, frame);
      push(`${def.id}-leaf`, def.wallX, midY, hingeAlong + leafDir * leafW / 2, LEAF_T, leafH, leafW, oak);
    }
  }
  for (const def of d.SLIDE_DOORS) {
    const openingW = Math.abs(def.alongMax - def.alongMin);
    const n = def.panels;
    const overlap = 0.04;
    const leafW = n === 2 ? (openingW + overlap) / 2 + 0.01 : openingW - 0.02;
    const leafH = def.height - 0.04;
    const baseY = d.FLOOR_LEVELS[def.floor ?? "1f"];
    const sillY = baseY + def.sill;
    const closedA = n === 2 ? def.alongMin + leafW / 2 - overlap * 0.25 : (def.alongMin + def.alongMax) / 2;
    const closedB = n === 2 ? def.alongMax - leafW / 2 + overlap * 0.25 : closedA;
    const frame = def.leaf ? "doorOak" : "doorFrame";
    const leafFinish = def.leaf ? "doorOak" : "glass";
    const y = sillY + 0.02 + leafH / 2;
    const thick = def.leaf ? 0.04 : 0.012;
    if (def.axis === "ew") {
      push(`${def.id}-a`, closedA, y, def.wallZ, leafW, leafH, thick, leafFinish);
      if (n === 2) push(`${def.id}-b`, closedB, y, def.wallZ, leafW, leafH, thick, leafFinish);
      push(`${def.id}-post-a`, def.alongMin, sillY + def.height / 2, def.wallZ, 0.028, def.height, T * 0.95, frame);
      push(`${def.id}-post-b`, def.alongMax, sillY + def.height / 2, def.wallZ, 0.028, def.height, T * 0.95, frame);
    } else {
      push(`${def.id}-a`, def.wallX, y, closedA, thick, leafH, leafW, leafFinish);
      if (n === 2) push(`${def.id}-b`, def.wallX, y, closedB, thick, leafH, leafW, leafFinish);
      push(`${def.id}-post-a`, def.wallX, sillY + def.height / 2, def.alongMin, T * 0.95, def.height, 0.028, frame);
      push(`${def.id}-post-b`, def.wallX, sillY + def.height / 2, def.alongMax, T * 0.95, def.height, 0.028, frame);
    }
  }
  for (const def of d.FOLD_DOORS) {
    const openingW = Math.abs(def.alongMax - def.alongMin);
    const baseY = d.FLOOR_LEVELS[def.floor ?? "1f"];
    const sillY = baseY + def.sill;
    const mid = (def.alongMin + def.alongMax) / 2;
    const leafH = def.height - 0.045;
    if (def.axis === "ew") {
      push(`${def.id}-leaf`, mid, sillY + leafH / 2, def.wallZ, openingW - 0.04, leafH, 0.04, "doorOak");
    } else {
      push(`${def.id}-leaf`, def.wallX, sillY + leafH / 2, mid, 0.04, leafH, openingW - 0.04, "doorOak");
    }
  }
}

function pushSite(push, d) {
  const g = d.GENKAN_ENTRY;
  const y0 = d.FLOOR_LEVELS["1f"];
  const p = d.PARKING_1F;
  push(
    "ground",
    d.BUILDING.width / 2,
    -0.08,
    d.BUILDING.depth / 2,
    d.BUILDING.width + 16,
    0.12,
    d.BUILDING.depth + 16,
    "ground",
  );
  push(
    "parking",
    p.x + p.width / 2,
    y0 - 0.01,
    p.z + p.depth / 2,
    p.width,
    0.02,
    p.depth,
    "parking",
  );
  const midX = (g.x0 + g.x1) / 2;
  const face = g.z - d.BUILDING.wallThickness / 2;
  for (let i = 0; i < g.stepCount; i++) {
    const level = i + 1;
    const topY = g.stepHeight * level;
    const centerY = topY - g.stepHeight / 2;
    const fromDoor = g.stepCount - i;
    const centerZ = face - g.stepDepth * (fromDoor - 0.5);
    push(`genkan-step-${i}`, midX, y0 + centerY, centerZ, g.stepWidth, g.stepHeight, g.stepDepth, "step");
  }
}

function pushRoofs(push, d) {
  const roofT = 0.08;
  const nwY = d.FLOOR_LEVELS["2f"];
  push(
    "roof-1f-nw",
    (d.SZ.yoshitsuW + d.X2.w1) / 2,
    nwY - roofT / 2,
    (d.Z2.clN + d.Z2.north) / 2,
    d.X2.w1 - d.SZ.yoshitsuW,
    roofT,
    d.Z2.north - d.Z2.clN,
    "roof",
  );
  pushShed(push, "roof-2f-ne", 6.37, d.BUILDING.width, d.Z2.clN, d.Z2.north, d.neRoomRoofY(d.Z2.clN), d.STORY.roofPitch, "roof");
  pushShed(push, "roof-ph-hall", d.IR.clE, d.SX.xLdkE, d.IR.mid, d.SZ.north, d.STORY.peak, d.STORY.roofPitch, "roofDark");

  const b = d.BALCONY_2F;
  for (const bay of [b.west, b.east]) {
    if (!bay) continue;
    const cx = (bay.x0 + bay.x1) / 2;
    const cz = (bay.z0 + bay.z1) / 2;
    push(
      `balc-soffit-${cx.toFixed(2)}`,
      cx,
      b.y - b.slabT - 0.006,
      cz,
      Math.abs(bay.x1 - bay.x0) - 0.02,
      0.012,
      Math.abs(bay.z1 - bay.z0) - 0.02,
      "stucco",
    );
  }
}

function pushShed(push, id, x0, x1, zS, zN, ySouth, pitch, finish) {
  const slices = 10;
  const t = 0.08;
  for (let i = 0; i < slices; i++) {
    const z0 = zS + ((zN - zS) * i) / slices;
    const z1 = zS + ((zN - zS) * (i + 1)) / slices;
    const y0 = ySouth - pitch * (z0 - zS);
    const y1 = ySouth - pitch * (z1 - zS);
    const y = (y0 + y1) / 2 - t / 2;
    push(`${id}-${i}`, (x0 + x1) / 2, y, (z0 + z1) / 2, Math.abs(x1 - x0), t, Math.abs(z1 - z0) + 0.02, finish);
  }
}

function heroList(d, ub, louver) {
  const g = d.GENKAN_ENTRY;
  const halfT = d.BUILDING.wallThickness / 2;
  const leafT = 0.052;
  const hingeX = g.x0 + 0.05;
  const leafZ = g.z - halfT + leafT / 2 + 0.002;
  const frameBaseY = d.FLOOR_LEVELS["1f"] + g.sill;
  const pi = d.PROP_1F_SENMEN.piara;
  const sen = d.PROP_1F_SENMEN;
  const sink = d.PROP_2F_SINK;
  const originX = sink.wallFaceX - sink.standoff - sink.counter.d;
  return [
    { file: "models/hero/genkan-door.glb", x: hingeX, y: frameBaseY, z: leafZ, yaw: 0 },
    { file: "models/hero/kitchen-noct.glb", x: d.PROP_1F_LDK_KITCHEN.originX, y: d.PROP_1F_LDK_KITCHEN.y, z: d.PROP_1F_LDK_KITCHEN.originZ, yaw: 0 },
    { file: "models/hero/ub-bath.glb", ...ub.ubOrigin(), yaw: 0 },
    { file: "models/hero/ub-louver.glb", ...louver.ubLouverOrigin(), yaw: 0 },
    {
      file: "models/hero/senmen-piara.glb",
      x: sen.vanity.x - pi.w / 2,
      y: sen.y,
      z: sen.wallFaceZ - pi.d,
      yaw: 0,
    },
    { file: "models/hero/amage-toilet.glb", x: d.PROP_1F_TOILET.x, y: d.PROP_1F_TOILET.y, z: d.PROP_1F_TOILET.z, yaw: 0 },
    { file: "models/hero/amage-toilet.glb", x: d.PROP_2F_TOILET.x, y: d.PROP_2F_TOILET.y, z: d.PROP_2F_TOILET.z, yaw: 0 },
    { file: "models/hero/dokodemo-wash.glb", x: originX, y: sink.y, z: sink.z, yaw: Math.PI / 2 },
  ];
}

function lightList(d) {
  const L = d.LIGHTING;
  const fills = L.interiorFills.map((f) => ({
    id: f.id,
    x: f.position[0],
    y: f.position[1],
    z: f.position[2],
    intensity: f.intensity,
    distance: f.distance,
    ...hexRgb(f.color),
  }));
  const extra = [L.genkanRecess.fill, L.genkanRecess.rakeWest];
  extra.forEach((f, i) => {
    fills.push({
      id: i === 0 ? "genkan-fill" : "genkan-rake",
      x: f.position[0],
      y: f.position[1],
      z: f.position[2],
      intensity: f.intensity,
      distance: f.distance,
      ...hexRgb(f.color),
    });
  });
  return fills;
}

function heightSamples(d, height) {
  const pts = [
    ["spawn", d.PLAYER.spawn.x, d.PLAYER.spawn.z, 0],
    ["ldk", 3, 3, d.INTERIOR_FLOOR_Y],
    ["ldk-from-grade", 3, 3, 0],
    ["genkan-sill", (d.GENKAN_ENTRY.x0 + d.GENKAN_ENTRY.x1) / 2, d.GENKAN_ENTRY.z + 0.3, d.INTERIOR_FLOOR_Y],
    ["outdoor-east", 12, -1, 0],
  ];
  const flight = d.STAIRS[0];
  if (flight) {
    const i = Math.floor(flight.stepCount / 2);
    let x = flight.x;
    let z = flight.z;
    const along = (i + 0.5) * flight.treadDepth;
    if (flight.direction === "north") z += along;
    else if (flight.direction === "south") z -= along;
    else if (flight.direction === "east") x += along;
    else x -= along;
    const feet = flight.baseY + i * flight.riserHeight;
    pts.push(["stair-mid", x, z, feet]);
    pts.push(["stair-mid-up", x, z, feet + flight.riserHeight]);
  }
  const w = d.STAIR_WINDERS[0];
  if (w) {
    const a = w.startAngle + w.sweep * 0.5;
    const r = (w.rInner + w.rOuter) / 2;
    pts.push([
      "winder-mid",
      w.pivotX + r * Math.cos(a),
      w.pivotZ + r * Math.sin(a),
      w.baseY + (w.stepCount / 2) * w.riserHeight,
    ]);
  }
  pts.push(["deck-2f", d.BUILDING.width * 0.5, d.BUILDING.depth * 0.75, d.STORY.floor2f]);
  pts.push(["ph", d.SX.xLdkE * 0.5, d.SZ.north - 0.4, d.STORY.floorPh]);
  return pts.map(([name, x, z, feet]) => ({
    name,
    x,
    z,
    feet,
    y: height.getGroundHeight(x, z, feet),
  }));
}
