// Generated by tools/kmp/export-spec.mjs --interact-only — do not edit numbers.
// Source: src/data/dimensions.ts, src/lib/ubBathHero.ts, src/lib/ubLouver.ts, src/lib/tubWater.ts
package com.neojou.japanesehouse3d.domain

object HouseInteract {
    const val swingDamp = 10.0
    const val slideDamp = 8.0
    const val foldDamp = 8.0
    const val genkanDamp = 10.0
    const val drawerDamp = 8.0
    const val streamDamp = 10.0
    const val louverDamp = 8.0
    const val toiletDamp = 7.0
    const val plugDamp = 14.0

    data class Swing(
        val id: String,
        val leafId: String,
        val axis: String,
        val hingeAt: String,
        val openSign: Int,
        val openAngleDeg: Double,
        val hingeX: Double,
        val hingeY: Double,
        val hingeZ: Double,
        val centerX: Double,
        val centerY: Double,
        val centerZ: Double,
        val sizeX: Double,
        val sizeY: Double,
        val sizeZ: Double,
    )

    data class Slide(
        val id: String,
        val axis: String,
        val overlap: Boolean,
        val panels: Int,
        val stack: Double,
        val pocketA: Double,
        val pocketB: Double,
        val leafA: String,
        val leafB: String,
    )

    data class Fold(
        val id: String,
        val leafId: String,
        val axis: String,
        val hingeAt: String,
        val openSign: Int,
        val openAngleDeg: Double,
        val hingeX: Double,
        val hingeY: Double,
        val hingeZ: Double,
        val panelW: Double,
        val leafW: Double,
        val leafH: Double,
        val thick: Double,
    )

    data class Genkan(
        val openRad: Double,
        val hingeX: Double,
        val hingeY: Double,
        val hingeZ: Double,
        val centerX: Double,
        val centerY: Double,
        val centerZ: Double,
        val sizeX: Double,
        val sizeY: Double,
        val sizeZ: Double,
    )

    val swings: List<Swing> = listOf(
        Swing("swing-1f-senmen-east", "swing-1f-senmen-east-leaf", "ns", "max", 1, 90.0, 10.845, 1.604, 6.02, 10.845, 1.604, 5.605, 0.04, 1.99, 0.83),
        Swing("swing-ldk-genkan", "swing-ldk-genkan-leaf", "ns", "max", 1, 85.0, 6.37, 1.554, 5.405, 6.37, 1.554, 5.015, 0.04, 1.89, 0.78),
        Swing("swing-2f-ne", "swing-2f-ne-leaf", "ns", "min", 1, 85.0, 6.37, 4.454, 3.64, 6.37, 4.454, 4.085, 0.04, 1.89, 0.89),
        Swing("swing-2f-sw", "swing-2f-sw-leaf", "ew", "max", -1, 85.0, 3.64, 4.454, 3.64, 3.195, 4.454, 3.64, 0.89, 1.89, 0.04),
        Swing("swing-2f-sc", "swing-2f-sc-leaf", "ew", "min", 1, 85.0, 3.64, 4.454, 3.64, 4.085, 4.454, 3.64, 0.89, 1.89, 0.04),
        Swing("swing-ta-1f", "swing-ta-1f-leaf", "ew", "min", -1, 90.0, 7.49, 1.554, 5.46, 7.83, 1.554, 5.46, 0.68, 1.89, 0.04),
        Swing("swing-ta-2f", "swing-ta-2f-leaf", "ew", "min", -1, 90.0, 3.85, 4.454, 5.46, 4.19, 4.454, 5.46, 0.68, 1.89, 0.04),
        Swing("swing-ph-balcony", "swing-ph-balcony-leaf", "ew", "min", -1, 90.0, 5.06, 7.254, 3.64, 5.45, 7.254, 3.64, 0.78, 1.89, 0.04),
    )

    val slides: List<Slide> = listOf(
        Slide("slide-1f-ldk-east", "ns", true, 2, 0.67, -0.6248, -1.136, "slide-1f-ldk-east-a", "slide-1f-ldk-east-b"),
        Slide("slide-1f-ldk-north", "ew", true, 2, 0.81, -0.748, -1.36, "slide-1f-ldk-north-a", "slide-1f-ldk-north-b"),
        Slide("slide-1f-yoshitsu-w", "ns", true, 2, 0.84, -0.7744, -1.408, "slide-1f-yoshitsu-w-a", "slide-1f-yoshitsu-w-b"),
        Slide("slide-2f-ne-balcony", "ew", true, 2, 1.04, -0.9504, -1.728, "slide-2f-ne-balcony-a", "slide-2f-ne-balcony-b"),
        Slide("slide-ub-shower", "ew", false, 2, 0.39, -0.3784, -0.688, "slide-ub-shower-a", "slide-ub-shower-b"),
        Slide("slide-1f-yoshitsu-pa", "ew", false, 1, 0.74, -0.6864, -1.248, "slide-1f-yoshitsu-pa-a", "slide-1f-yoshitsu-pa-b"),
        Slide("slide-1f-senmen-dc", "ns", false, 1, 0.74, 0.6864, 1.248, "slide-1f-senmen-dc-a", "slide-1f-senmen-dc-b"),
    )

    val folds: List<Fold> = listOf(
        Fold("fold-1f-scl", "fold-1f-scl-leaf", "ns", "min", 1, 78.0, 7.89, 0.609, 3.24, 0.45, 0.447, 1.905, 0.04),
        Fold("fold-1f-ldk-mono", "fold-1f-ldk-mono-leaf", "ns", "min", -1, 78.0, 5.915, 0.609, 0.075, 0.6075, 0.6045, 1.905, 0.04),
        Fold("fold-2f-mono", "fold-2f-mono-leaf", "ns", "min", -1, 68.0, 3.23, 3.509, 4.625, 0.38, 0.377, 1.905, 0.04),
        Fold("fold-2f-cl-s", "fold-2f-cl-s-leaf", "ns", "min", -1, 78.0, 3.64, 3.509, 0.075, 0.6075, 0.6045, 1.905, 0.04),
        Fold("fold-2f-cl-n", "fold-2f-cl-n-leaf", "ns", "min", 1, 78.0, 2.73, 3.509, 1.44, 0.6075, 0.6045, 1.905, 0.04),
        Fold("fold-2f-ne-cl", "fold-2f-ne-cl-leaf", "ns", "max", -1, 78.0, 7.28, 3.509, 6.295, 0.835, 0.832, 1.905, 0.04),
        Fold("fold-1f-stair-mono", "fold-1f-stair-mono-leaf", "ew", "min", -1, 78.0, 5.535, 0.609, 5.46, 0.38, 0.377, 1.905, 0.04),
    )

    val genkan = Genkan(1.483529864, 6.42, 1.574, 2.783, 7.13, 1.574, 2.783, 1.42, 1.93, 0.052)

    const val kitchenDrawerTravel = 0.38
    const val kitchenStreamX = 0.4
    const val kitchenStreamY = 0.86
    const val kitchenStreamZ = 1.46
    const val kitchenStreamH = 0.26
    const val kitchenStreamR0 = 0.004
    const val kitchenStreamR1 = 0.005

    const val piaraDrawerTravel = 0.34
    const val piaraDoorOpen = 1.431169987
    const val piaraMirrorOpen = 1.535889742
    const val piaraStreamX = 0.4025
    const val piaraStreamY = 0.778
    const val piaraStreamZ = 0.2945
    const val piaraStreamH = 0.235

    const val louverClosedDeg = 8.0
    const val louverOpenDeg = 88.0
    const val louverSliderTravel = 0.28

    const val lidOpenRad = 1.919862177
    const val seatOpenRad = 1.658062789

    const val dokoStreamX = 0.005
    const val dokoStreamY = 0.915
    const val dokoStreamZ = 0.18
    const val dokoStreamH = 0.12

    const val tubFillRate = 0.12
    const val tubDrainRate = 0.32
    const val tubSpreadRate = 0.085
    const val tubDryRate = 0.05

    data class Tub(
        val x: Double,
        val y: Double,
        val z: Double,
        val length: Double,
        val width: Double,
        val innerW: Double,
        val innerL: Double,
        val bottomY: Double,
        val brimY: Double,
        val spillY: Double,
        val plugTravel: Double,
        val buttonTravel: Double,
        val tipX: Double,
        val tipY: Double,
        val tipZ: Double,
        val holeX: Double,
        val holeY: Double,
        val holeZ: Double,
        val r: Double,
        val g: Double,
        val b: Double,
        val a: Double,
    )

    val tub = Tub(10.412, 0.609, 3.445, 1.2, 0.7, 0.62, 1.12, 0.751, 1.131, 1.151, 0.016, 0.003, 10.372, 1.179, 2.905, 10.412, 0.745, 2.975, 0.556862745, 0.721568627, 0.784313725, 0.58)

    val animatedBoxIds: Set<String> = setOf(
        "swing-1f-senmen-east-leaf",
        "swing-ldk-genkan-leaf",
        "swing-2f-ne-leaf",
        "swing-2f-sw-leaf",
        "swing-2f-sc-leaf",
        "swing-ta-1f-leaf",
        "swing-ta-2f-leaf",
        "swing-ph-balcony-leaf",
        "slide-1f-ldk-east-a",
        "slide-1f-ldk-east-b",
        "slide-1f-ldk-north-a",
        "slide-1f-ldk-north-b",
        "slide-1f-yoshitsu-w-a",
        "slide-1f-yoshitsu-w-b",
        "slide-2f-ne-balcony-a",
        "slide-2f-ne-balcony-b",
        "slide-ub-shower-a",
        "slide-ub-shower-b",
        "slide-1f-yoshitsu-pa-a",
        "slide-1f-senmen-dc-a",
        "fold-1f-scl-leaf",
        "fold-1f-ldk-mono-leaf",
        "fold-2f-mono-leaf",
        "fold-2f-cl-s-leaf",
        "fold-2f-cl-n-leaf",
        "fold-2f-ne-cl-leaf",
        "fold-1f-stair-mono-leaf",
    )
}
